*** empty log message ***

diff --git a/command-processor b/command-processor
--- a/command-processor
+++ b/command-processor
@@ -20,9 +20,12 @@
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 
-# $Id: command-processor,v 1.3 2009/04/09 12:08:45 bhepple Exp $
+# $Id: command-processor,v 1.4 2009/04/10 09:46:18 bhepple Exp $
 
 # A test script for process-getopt - just echos options and args
+
+# error on first failed command or unreferencing a undefined variable:
+set -eu
 
 check_and_process_opts() {
     local NO_OPTS TEMP PG
@@ -32,32 +35,30 @@ check_and_process_opts() {
     source $PG
 
     # option helper functions:
-    SLOT_func() { [ "$1" ] && SLOT="yes" && echo VERBOSE=$SOPT_VERBOSE; }
+    SLOT_func() { [ "${1:-""}" ] && SLOT="yes"; }
     add_opt SLOT "boolean option" s "" slot 
 
-    TOKEN_func() { [ "$1" ] && TOKEN="$2"; }
+    TOKEN_func() { [ "${1:-""}" ] && TOKEN="$2"; }
     add_opt TOKEN "option that takes a value" t n token number
 
-    LONGONLY_func() { [ "$1" ] && LONGONLY="$2"; }
+    LONGONLY_func() { [ "${1:-""}" ] && LONGONLY="$2"; }
     add_opt LONGONLY "long option without short option" "" "" "long-only" "value"
-    COUNTED_func() {  [ "$1" ] && (( COUNTED++ )); }
+    COUNTED_func() {  [ "${1:-""}" ] && (( COUNTED++ )); }
     add_opt COUNTED "an option which increments every time it is given" c
 
     add_std_opts # define the standard options --help etc
+    del_opt QUIET VERBOSE
 
     TEMP=$(call_getopt "$@") || exit 1
     eval set -- "$TEMP"
-    process_opts "$@"
-    shift "$?"
+    process_opts "$@" || shift "$?"
     NEW_ARGS=( "$@" )
     return 0
 }
 
 process_add_options() {
     # option helper functions:
-    clean_process_getopt
-    ADDSLOT=""
-    ADDSLOT_func() { [ "$1" ] && ADDSLOT="yes"; }
+    ADDSLOT_func() { [ "${1:-""}" ] && ADDSLOT="yes"; }
     add_opt ADDSLOT "boolean option" s "" add-slot 
 
     add_std_opts # define the standard options --help etc
@@ -66,7 +67,7 @@ process_add_options() {
     export STOP_ON_FIRST_NON_OPT="yes"
     TEMP=$(call_getopt "$@") || exit 1
     eval set -- "$TEMP"
-    process_opts "$@"; shift "$?"
+    process_opts "$@" || shift "$?"
     NEW_ARGS=( "$@" )
 }
 
@@ -76,7 +77,7 @@ process_add_options() {
 
 PROG=$(basename $0)
 DIR=$(dirname $0)
-VERSION="$Revision: 1.3 $"
+VERSION='$Revision: 1.4 $'
 VERBOSE=""
 ARGUMENTS="add | multiply | frob | bris [ COMMAND_OPTIONS] "
 USAGE="echos options and args to stdout"
@@ -90,13 +91,14 @@ COUNTED=0
 
 export STOP_ON_FIRST_NON_OPT="yes"
 NEW_ARGS=( )
-check_and_process_opts "$@" && set -- "${NEW_ARGS[@]}"
+check_and_process_opts "$@" 
+set -- "${NEW_ARGS[@]:-""}"
 
 # At this point, all the options have been processed and removed from
 # the arg list. We can now process $@ as arguments to the program.
 
 echo "After global option processing we have:"
-for i in "$@"; do echo -n " \"$i\""; done
+for i in "$@"; do echo -n "\"$i\" "; done
 echo
 
 # $@ now contains only the command and its options
@@ -107,25 +109,28 @@ echo
 [ "$COUNTED" -gt 0 ] && echo "COUNTED option (-$(get_opt_letter COUNTED) = $COUNTED)"
 [ "$VERBOSE" ] && echo "VERBOSE option (-$(get_opt_letter VERBOSE), --$(get_opt_string VERBOSE))"
 
-COMMAND="$1"
-shift
+# at this point we've processed all the options before the first argument - so 
+# now we can set up and process the argument and its options:
 
-case $COMMAND in
+clean_process_getopt
+
+COMMAND="${1:-""}"
+shift
+echo "COMMAND=$COMMAND"
+
+case "$COMMAND" in
     add) 
         NEW_ARGS=( )
         PROG="$PROG add"
         USAGE="do the add thing"
+        ADDSLOT=""
         process_add_options "$@"
-        set -- "${NEW_ARGS[@]}"
-        echo "After add option processing we have:"
+        [ ${#NEW_ARGS[@]} -gt 0 ] && set -- "${NEW_ARGS[@]}"
+        echo "After 'add' option processing we have:"
         for i in "$@"; do echo -n " \"$i\""; done
         echo
-
-        [ "$SLOT" ] && echo "SLOT option (-$(get_opt_letter SLOT), --$(get_opt_string SLOT))"
-        [ "$TOKEN" ] && echo "TOKEN option (-$(get_opt_letter TOKEN) \"$TOKEN\", --$(get_opt_string TOKEN)=\"$TOKEN\")"
-        [ "$LONGONLY" ] && echo "LONGONLY option (--$(get_opt_string LONGONLY)=\"$LONGONLY\")"
-        [ "$COUNTED" -gt 0 ] && echo "COUNTED option (-$(get_opt_letter COUNTED) = $COUNTED)"
-        [ "$VERBOSE" ] && echo "VERBOSE option (-$(get_opt_letter VERBOSE), --$(get_opt_string VERBOSE))"
+        echo "ADDSLOT=$ADDSLOT"
+        echo "ADDSLOT option (-$(get_opt_letter ADDSLOT), --$(get_opt_string ADDSLOT))"
         ;;
     *)
 esac
diff --git a/process-getopt b/process-getopt
--- a/process-getopt
+++ b/process-getopt
@@ -19,7 +19,7 @@
 # http://process-getopt.sourceforge.net
 # http://bhepple.freeshell.org/oddmuse/wiki.cgi/process-getopt
 
-# $Id: process-getopt,v 1.22 2009/04/09 12:15:23 bhepple Exp $
+# $Id: process-getopt,v 1.23 2009/04/10 09:46:18 bhepple Exp $
 
 # A wrapper around getopt.
 
@@ -142,7 +142,7 @@ process_getopt_usage() {
 # again to process the command options. 
 clean_process_getopt() {
     unset ${!SOPT*} ${!LOPT*} ${!DESC_OPT*} ${!ARG_SOPT*} ${!ARG_LOPT*}
-    unset __PG_OPTION_LIST
+    __PG_OPTION_LIST=""
 }
 
 process_getopt_version() {
@@ -151,12 +151,13 @@ process_getopt_version() {
 
 add_opt() {
     # parameters: use "" as the placeholder for a missing arg
-    local NAME="$1" ; shift # name of the option - essential
-    local DESC="$1" ; shift # essential except for 'silent/secret' options
-    local SOPT="$1" ; shift # short option letter - optional
-    local SARG="$1" ; shift # argument label for the short option - optional
-    local LOPT="$1" ; shift # long option - optional
-    local LARG="$1" ; shift # argument label for the long option - optional
+    local NAME DESC SOPT SARG LOPT LARG
+    NAME="$1" # name of the option - essential
+    DESC="$2" # essential except for 'silent/secret' options
+    SOPT="${3:-""}" # short option letter - optional
+    SARG="${4:-""}" # argument label for the short option - optional
+    LOPT="${5:-""}" # long option - optional
+    LARG="${6:-""}" # argument label for the long option - optional
     local A
     local L
     local ALLOWED_CHARS='[a-zA-Z0-9_][a-zA-Z0-9_]*'
@@ -178,8 +179,11 @@ add_opt() {
         exit 1
     }
 
-    # check that a helper function is available:
-    ${NAME}$FUNC_SUFFIX 2>/dev/null; local STAT=$?
+    # check that a helper function is available by calling it without an arg
+    # it is supposed to do nothing - but if it is undefined then we get
+    # error 127:
+    local STAT=0
+    ${NAME}$FUNC_SUFFIX 2>/dev/null || STAT=$?
     if [ $STAT -eq 127 ]; then
         echo "$PROG: process-getopt: option $NAME has no helper function $NAME$FUNC_SUFFIX" >&2
         exit 1
@@ -202,7 +206,7 @@ add_opt() {
         if [ "$SOPT" ]; then
             for SUFFIX in "" "A"; do
                 L="SOPT${SUFFIX}_$OPT"
-                if [ "$SOPT" = "${!L}" ]; then
+                if [ "$SOPT" = "${!L:-""}" ]; then
                     echo "$PROG: process-getopt: short option \"$SOPT\" is already in use by \
 $OPT" >&2
                     exit 1
@@ -212,7 +216,7 @@ $OPT" >&2
         if [ "$LOPT" ]; then
             for SUFFIX in "" "A"; do
                 L="LOPT${SUFFIX}_$OPT"
-                if [ "$LOPT" = "${!L}" ]; then
+                if [ "$LOPT" = "${!L:-""}" ]; then
                     echo "$PROG: process-getopt: long option \"$LOPT\" is already in use by $OPT" >&2
                     exit 1
                 fi
@@ -244,50 +248,52 @@ get_opt_letter() {
     local NAME="$1"
     local L="SOPT_$NAME" 
     
-    [ "${!L}" ] || L="SOPTA_$NAME"
-    echo -n  "${!L}"
+    [ "${!L:-""}" ] || L="SOPTA_$NAME"
+    echo -n  "${!L:-""}"
 }
 
 get_opt_string() {
     local NAME="$1"
     local L="LOPT_$NAME" 
     
-    [ "${!L}" ] || L="LOPTA_$NAME"
-    echo -n  "${!L}"
+    [ "${!L:-""}" ] || L="LOPTA_$NAME"
+    echo -n  "${!L:-""}"
 }
 
 get_opt_sarg() {
     local NAME="$1"
     local L="ARG_SOPTA_$NAME" 
     
-    echo -n "${!L}"
+    echo -n "${!L:-""}"
 }
 
 get_opt_larg() {
     local NAME="$1"
     local L="ARG_LOPTA_$NAME" 
     
-    echo -n "${!L}"
+    echo -n "${!L:-""}"
 }
 
 get_opt_desc() {
     local NAME="$1"
     local L="DESC_OPT_$NAME" 
     
-    echo -n "${!L}"
+    echo -n "${!L:-""}"
 }
 
 del_opt() {
-    local NAME="$1"
-    for PRE in SOPT_ SOPTA_ LOPT_ LOPTA_ DESC_OPT_ ARG_LOPTA_ ARG_SOPTA_; do
-        unset $PRE$NAME
+    local NAME
+    for NAME in "$@"; do
+        for PRE in SOPT_ SOPTA_ LOPT_ LOPTA_ DESC_OPT_ ARG_LOPTA_ ARG_SOPTA_; do
+            unset $PRE$NAME
+        done
+        local OPT_LIST
+        OPT_LIST=""
+        for OPT in $__PG_OPTION_LIST; do
+            [ $OPT = $NAME ] || OPT_LIST="$OPT_LIST $OPT"
+        done
+        __PG_OPTION_LIST="$OPT_LIST"
     done
-    local OPT_LIST
-    OPT_LIST=""
-    for OPT in $__PG_OPTION_LIST; do
-        [ $OPT = $NAME ] || OPT_LIST="$OPT_LIST $OPT"
-    done
-    __PG_OPTION_LIST="$OPT_LIST"
 }
 
 # prints only short options that take no parameter
@@ -361,7 +367,7 @@ print_long_args() {
 
 # prints short and long options that take a parameter
 print_all_args() {
-    local MAN=$1
+    local MAN=${1:-""}
 
     local NAME
     for NAME in $__PG_OPTION_LIST; do 
@@ -439,7 +445,7 @@ print_man_page() {
     ARGS=$(print_all_args man)
 
     cat <<EOF
-.\" $Id: process-getopt,v 1.22 2009/04/09 12:15:23 bhepple Exp $
+.\" $Id: process-getopt,v 1.23 2009/04/10 09:46:18 bhepple Exp $
 .TH `echo $PROG|tr '[a-z]' '[A-Z]'` 1 \" -*- nroff -*-
 .SH NAME
 $PROG \- $SHORT_DESC
@@ -447,11 +453,11 @@ $PROG \- $SHORT_DESC
 .hy 0
 .na
 .B $PROG$FLAGS$LFLAGS$ARGS
-$ARGUMENTS
+${ARGUMENTS:-""}
 .ad b
 .hy 0
 .SH DESCRIPTION
-$USAGE
+${USAGE:-""}
 .P
 Foobar foobar foobar
 .SH OPTIONS
@@ -571,7 +577,7 @@ print_opt() {
     if [ "$__PG_LONG_GETOPT" ]; then
         [ "$SOPT" ] && [ "$LOPT" ] && LINE="$LINE, "
         if [ "$LOPT" ]; then
-            [ "$SOPT" ] && LONG_START=$LONG_COL_OPT || LONG_START=$__PG_SHORT_OPT_COL
+            [ "$SOPT" ] && LONG_START=${LONG_COL_OPT:-""} || LONG_START=$__PG_SHORT_OPT_COL
             for (( N=0 ; ${#LINE} < LONG_START ; N++ )); do 
                 LINE="$LINE "
             done
@@ -608,7 +614,7 @@ print_opt() {
 
 # honour GNU ARGP_HELP_FMT parameter
 load_help_fmt() {
-    [ "$ARGP_HELP_FMT" ] || return 0
+    [ "${ARGP_HELP_FMT:-""}" ] || return 0
     OFS="$IFS"
     IFS=','
     set -- $ARGP_HELP_FMT
@@ -646,9 +652,9 @@ default_usage() {
     local ARGS=$(print_all_args)
     local FMT="fmt -w $__PG_COLUMNS -s"
     type fmt &> /dev/null || FMT=cat
-    echo "Usage: $PROG $FLAGS$LFLAGS$ARGS $ARGUMENTS" |$FMT
+    echo "Usage: $PROG $FLAGS$LFLAGS$ARGS ${ARGUMENTS:-""}" |$FMT
     echo
-    echo "$SHORT_DESC$USAGE" |$FMT
+    echo "${SHORT_DESC:-""}${USAGE:-""}" |$FMT
     echo
     echo "Options:"
     print_all_opts
@@ -657,7 +663,7 @@ default_usage() {
 process_opts() {
     local SHIFT_NUM=0
     while true; do
-        case $1 in
+        case "${1:-""}" in
         -$HELP_option | --$HELP_loption) 
             usage 2>/dev/null || default_usage
             exit 0
@@ -704,14 +710,13 @@ process_opts() {
             # now let's adjust for options with args:
             local SA="ARG_SOPTA_$NAME"
             local LA="ARG_LOPTA_$NAME"
-            if [ "${!SA}${!LA}" ]; then
+            if [ "${!SA:-""}${!LA:-""}" ]; then
                 shift
                 ((SHIFT_NUM++))
             fi
             ;;
         esac
     done
-    clean_process_getopt
     return $SHIFT_NUM
 }
 
@@ -724,10 +729,10 @@ get_opt_name() {
         local LA=LOPTA_$NAME
         local S=SOPT_$NAME
         local SA=SOPTA_$NAME
-        if  [ "--${!L}" = "$OPT" ] || \
-            [ "--${!LA}" = "$OPT" ] || \
-            [ "-${!S}" = "$OPT" ] || \
-            [ "-${!SA}" = "$OPT" ]; then
+        if  [ "--${!L:-""}" = "$OPT" ] || \
+            [ "--${!LA:-""}" = "$OPT" ] || \
+            [ "-${!S:-""}" = "$OPT" ] || \
+            [ "-${!SA:-""}" = "$OPT" ]; then
             echo "${NAME}"
             return 0
         fi
@@ -735,7 +740,7 @@ get_opt_name() {
     return 1
 }
 
-__PG_VERSION="1.4"
+__PG_VERSION="1.5"
 __PG_STANDALONE=""
 
 # First some safety checks:
@@ -758,7 +763,7 @@ __PG_STANDALONE=""
 }
 
 __PG_COLUMNS=`tput cols 2>/dev/null` || __PG_COLUMNS=80
-(( _PG_COLUMNS--))
+((__PG_COLUMNS--))
 
 __PG_OPTION_LIST=""
 __PG_LONG_GETOPT=""
@@ -805,3 +810,6 @@ load_help_fmt
     process_opts "$@"
     shift "$?"
 }
+
+# just to make sure we don't return with non-zero $?:
+:
diff --git a/tiny b/tiny
--- a/tiny
+++ b/tiny
@@ -20,25 +20,38 @@
 # http://process-getopt.sourceforge.net
 # http://bhepple.freeshell.org/oddmuse/wiki.cgi/process-getopt
 
-# $Id: tiny,v 1.1 2009/04/09 12:08:45 bhepple Exp $
+# $Id: tiny,v 1.2 2009/04/10 09:46:18 bhepple Exp $
+
+# error on first failed command or unreferencing a undefined variable:
+set -eu
 
 PROG=$(basename $0)
-VERSION="$Revision: 1.1 $"
+VERSION='$Revision: 1.2 $'
 USAGE="A tiny example using process-getopt(1)"
 
 # call process-getopt functions to define some options:
 source ./process-getopt
-SLOT_func()   { [ "$1" ] && SLOT="yes"; }      # callback for SLOT option
+
+SLOT=""
+SLOT_func()   { [ "${1:-""}" ] && SLOT="yes"; }      # callback for SLOT option
 add_opt SLOT "boolean option" s "" slot
-TOKEN_func()  { [ "$1" ] && TOKEN="$2"; }      # callback for TOKEN option
+
+TOKEN=""
+TOKEN_func()  { [ "${1:-""}" ] && TOKEN="$2"; }      # callback for TOKEN option
 add_opt TOKEN "this option takes a value" t n token number
+
 add_std_opts     # define the standard options --help etc:
 
-# The next 4 lines call the callbacks and remove the options from the command line # so all we need to deal with in the rest of our script is the arguments in $@
+# The next 4 lines call the callbacks and remove the options from the
+# command line so all we need to deal with in the rest of our script
+# is the arguments in $@
+
+# Re-order options and call option callbacks:
 TEMP=$(call_getopt "$@") || exit 1
 eval set -- "$TEMP"
-process_opts "$@" 
-shift "$?"    # remove the options from the command line
+
+# remove the options from the command line
+process_opts "$@" || shift "$?"
 
 echo "SLOT=$SLOT"
 echo "TOKEN=$TOKEN"
